import type { Bindings } from "../lib/types";

export interface VoiceReference {
  rules: {
    voice_is: string[];
    voice_is_not: string[];
    banned_words: string[];
    cast?: unknown;
  };
  samples: {
    email_to_member?: string[];
    trip_notes?: string[];
    cold_open_vo?: string[];
    build_vo?: string[];
    meaning_bridge_vo?: string[];
    [k: string]: string[] | undefined;
  };
  outreach_calibration_note?: string;
  version?: string;
  updated?: string;
}

export async function loadVoiceReference(env: Bindings): Promise<VoiceReference> {
  const raw = await env.SECRETS.get("voice_reference");
  if (!raw) {
    throw new Error("voice_reference not set in KV namespace SECRETS");
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (e) {
    throw new Error(
      "voice_reference KV value is not valid JSON: " +
        (e instanceof Error ? e.message : String(e)),
    );
  }
  if (typeof parsed !== "object" || parsed === null) {
    throw new Error("voice_reference must be a JSON object");
  }
  const v = parsed as Partial<VoiceReference>;
  if (
    !v.rules ||
    !Array.isArray(v.rules.voice_is) ||
    !Array.isArray(v.rules.voice_is_not) ||
    !Array.isArray(v.rules.banned_words)
  ) {
    throw new Error(
      "voice_reference.rules must contain voice_is[], voice_is_not[], banned_words[]",
    );
  }
  if (!v.samples || typeof v.samples !== "object") {
    throw new Error("voice_reference.samples is required");
  }
  return v as VoiceReference;
}

const formatCast = (cast: unknown): string => {
  if (typeof cast === "string") return cast;
  if (Array.isArray(cast)) return cast.join("; ");
  if (cast && typeof cast === "object") {
    return Object.entries(cast as Record<string, unknown>)
      .map(([k, val]) => `${k}: ${typeof val === "string" ? val : JSON.stringify(val)}`)
      .join("; ");
  }
  return "(unspecified)";
};

const formatSamples = (items: string[] | undefined, limit?: number): string => {
  if (!items || items.length === 0) return "(none provided)";
  const slice = limit ? items.slice(0, limit) : items;
  return slice.map((s, i) => `--- sample ${i + 1} ---\n${s}`).join("\n\n");
};

export function buildOutreachSystemPrompt(v: VoiceReference): string {
  const calibrationNote =
    v.outreach_calibration_note ??
    "voice_reference Section 2.9 (Brand Outreach Samples) is empty. Calibrate from email-to-member and trip notes registers. Drafts will need editing on first batch.";

  return `You draft brand outreach emails for Blackwater Outdoor Journeys (BWJ).
BWJ is a YouTube channel about wilderness paddling in the Southeast.
Founder: Rodney Thompson. Co-stars: Tina (partner), River Dog (canoe dog), Whitley (other dog, sometimes home).

VOICE RULES (voice_is):
${v.rules.voice_is.map((r) => `- ${r}`).join("\n")}

VOICE-IS-NOT (voice_is_not):
${v.rules.voice_is_not.map((r) => `- ${r}`).join("\n")}

BANNED WORDS (NEVER USE):
${v.rules.banned_words.join(", ")}

CAST NAMING:
${formatCast(v.rules.cast)}

OUTPUT RULES:
- Subject line: reference a specific thing — a place, a question, a piece of footage, a specific topic. Avoid meta-descriptions of the email itself ("a real conversation", "an introduction", "a quick note", "reaching out"). The subject is information, not announcement.
- DO NOT include contact details, phone, email, channel URL, or media kit link in the body. End the body at the personal sign-off line (e.g., "Rodney") only. The signature block is template, not voice — it gets appended by the system, not generated by you.

Voice calibration samples (study these for cadence — DO NOT copy phrasing):

EMAIL-TO-MEMBER samples (closest register to outreach):
${formatSamples(v.samples.email_to_member)}

TRIP-NOTES samples (unpolished baseline voice):
${formatSamples(v.samples.trip_notes)}

COLD-OPEN-VO samples (for sensory specificity reference):
${formatSamples(v.samples.cold_open_vo, 2)}

FIRST-BATCH WARNING: ${calibrationNote}`;
}

export interface OutreachUserPromptArgs {
  name: string;
  category: string | null;
  fit_reason: string | null;
  context_notes?: string | null;
}

export function buildOutreachUserPrompt(args: OutreachUserPromptArgs): string {
  const ctx =
    args.context_notes && args.context_notes.trim()
      ? args.context_notes.trim()
      : "first contact";
  return `Draft an outreach email to ${args.name} (${args.category ?? "uncategorized"}).
Fit reason: ${args.fit_reason ?? "not provided"}
Context: ${ctx}

Output strict JSON: {subject: string under 50 chars, body: string under 200 words}`;
}

// Any [...] up to 100 chars, no newlines inside. For plaintext outreach
// every such pattern is a placeholder token ("[contact info]", "[your email]").
// Markdown link syntax would be collateral, but we don't ask for markdown.
const PLACEHOLDER_PATTERN = /\[[^\]\n]{1,100}\]/g;

export function stripPlaceholders(text: string): string {
  let result = text.replace(PLACEHOLDER_PATTERN, "");
  result = result.split("\n").map((l) => l.replace(/[ \t]+$/, "")).join("\n");
  result = result.replace(/\n{3,}/g, "\n\n");
  return result.trim();
}

const escapeRegex = (s: string): string => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

export function findBannedWords(text: string, banned: string[]): string[] {
  const found: string[] = [];
  const lower = text.toLowerCase();
  for (const word of banned) {
    const w = word.trim();
    if (!w) continue;
    let hit = false;
    if (w.includes(" ")) {
      // Multi-word phrases: case-insensitive substring is correct
      hit = lower.includes(w.toLowerCase());
    } else {
      // Single words: word-boundary regex avoids false positives
      hit = new RegExp(`\\b${escapeRegex(w)}\\b`, "i").test(text);
    }
    if (hit && !found.includes(word)) found.push(word);
  }
  return found;
}
